apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-deployment
spec:
  replicas: {{ .Values.application.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-java-pod
    spec:
      containers:
      - name: java-container
        image: {{ .Values.application.image.name }}:{{ .Values.application.image.tag }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: java-configmap  
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 10m
  selector:
    matchLabels:
      app: {{ .Release.Name }}-java-pod