{{ if .Values.application.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-java
spec:
  ingressClassName: { .Values.application.ingress.className }
  rules:
  {{- range .Values.application.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $.Release.Name }}-java-app-service
            port:
              number: 80
  {{ end }}
{{ end }}