apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-app-service
spec:
  type: {{ .Values.application.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: {{ .Release.Name }}-java-pod